# Generated by Django 4.2.6 on 2024-01-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roungnakhone_hotel', '0002_room_name_alter_room_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='name',
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
